name: Documentation Improvement
description: Suggest improvements to documentation
title: "[Docs] "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve our documentation! Please describe the suggested changes.
  - type: dropdown
    id: file-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - Main README.md
        - Distribution-specific README (Arch/Debian/Fedora/Void)
        - Script comments or inline documentation
        - Repository structure documentation
        - Other
    validations:
      required: true
  - type: input
    id: file
    attributes:
      label: Affected File
      description: Which specific file needs improvement?
      placeholder: e.g., Arch/README.md or shell/auto_installers/install_essentials.sh
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue or improvement needed in the documentation.
      placeholder: The Arch README is missing information about [specific script]. It should include [suggestion].
    validations:
      required: true
  - type: textarea
    id: proposed-changes
    attributes:
      label: Proposed Changes
      description: Suggest specific changes or provide revised text.
      placeholder: |
        Current text: "..."
        Suggested text: "..."
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other context or references.
      placeholder: Include links to relevant documentation standards, examples from other projects, or specific sections that need updating.
    validations:
      required: false